# Numpy: Numerical python. 
Numpy's array objects as the lingua franca for the data exchange.
1. ndarray: multidimensional array providing fast array- oriented airthmetic operations and flexible broadcasting operations.
2. Mathematical functions for fast operation on entire arrays of data without writting loops.
3.  Tools for reading/writting array data to disk and working with memmory-mapped files.
4. Linear algebra, random number generation and fourier transform capabilities. 

NumPy provides easy to use C API, to pass data to external libraries written in low-level languages.  
5. It is designed for efficienctyon large arrays of data. 

In [2]:
import numpy as np
myaray= np.arange(1000000)
my_list= list(range(1000000))

# numpy based algorithms are generally 10 to 100 times faster than pure -python counterparts and use less memory.
%time for i in range(10): myaray2= myaray*2
%time for j in range(10): my_list2=[x*2 for x in my_list]

CPU times: total: 0 ns
Wall time: 19 ms
CPU times: total: 62.5 ms
Wall time: 422 ms


In [3]:
# N-dimensional array object or ndarray which is fast, flexible container for large datasets in python.
data=np.random.randn(2,5)
data*10
data+data

array([[ 2.13901815, -1.51887991, -0.34150388,  1.63804391, -0.0829884 ],
       [-1.34887962,  1.57999462,  5.91122049, -1.97174227,  0.74196738]])

In [4]:
# all elements must be same type. Every array has shape, a tuple indicating the size of each dimension, and a dtype, an object describing the datatype of the array. 
data.shape
data.dtype

# "array","Numpy array" or "ndarray" in the text with few exceptions they all refere to the smae thing: the ndarray object.

dtype('float64')

In [5]:
# creating ndarrays:

data1=[6,7,8,9.1]
arr1=np.array(data1)
arr1

array([6. , 7. , 8. , 9.1])

In [6]:
# nested sequence, like a list of equal length lists, will be converted into a multidimensional array.

data2=[[1,2,3,4],[4,5,6,7]]
array2=np.array(data2)
array2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [8]:
# the numpy array has two-dimensions with shape intended from the data. 
array2.ndim #2 is answer
array2.shape

(2, 4)

In [ ]:
# There are other function to create arrays. for eg: zeroes and ones to create 0s and 1s respectively, with given length or shape. 

np.zeros(3)
np.ones((1,2))
np.empty((2,3))

#similarly arange is an array value based version of built in python range functions #which is used in first example. 
# Since numpy is focused on numerical computing, the data type, if not specified it will return float64 in many cases.

array([[0., 0., 0.],
       [0., 0., 0.]])