# Numpy: Numerical python. 
Numpy's array objects as the lingua franca for the data exchange.
1. ndarray: multidimensional array providing fast array- oriented airthmetic operations and flexible broadcasting operations.
2. Mathematical functions for fast operation on entire arrays of data without writting loops.
3.  Tools for reading/writting array data to disk and working with memmory-mapped files.
4. Linear algebra, random number generation and fourier transform capabilities. 

NumPy provides easy to use C API, to pass data to external libraries written in low-level languages.  
5. It is designed for efficienctyon large arrays of data. 

In [1]:
import numpy as np
myaray= np.arange(1000000)
my_list= list(range(1000000))

# numpy based algorithms are generally 10 to 100 times faster than pure -python counterparts and use less memory.
%time for i in range(10): myaray2= myaray*2
%time for j in range(10): my_list2=[x*2 for x in my_list]

CPU times: total: 0 ns
Wall time: 11.2 ms
CPU times: total: 78.1 ms
Wall time: 413 ms


In [2]:
# N-dimensional array object or ndarray which is fast, flexible container for large datasets in python.
import numpy as np
data=np.random.randn(2,5)
data*10
data+data

array([[-3.17576931,  2.27312334, -0.82585202, -1.5619827 , -0.55464638],
       [ 4.74150781,  2.06285538,  0.82883988,  0.46834231, -0.21819372]])

In [3]:
# all elements must be same type. Every array has shape, a tuple indicating the size of each dimension, and a dtype, an object describing the datatype of the array. 
data.shape
data.dtype

# "array","Numpy array" or "ndarray" in the text with few exceptions they all refere to the smae thing: the ndarray object.

dtype('float64')

In [4]:
# creating ndarrays:

data1=[6,7,8,9.1]
arr1=np.array(data1)
arr1

array([6. , 7. , 8. , 9.1])

In [5]:
# nested sequence, like a list of equal length lists, will be converted into a multidimensional array.

data2=[[1,2,3,4],[4,5,6,7]]
array2=np.array(data2)
array2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [6]:
# the numpy array has two-dimensions with shape intended from the data. 
array2.ndim #2 is answer
array2.shape

(2, 4)

In [7]:
# There are other function to create arrays. for eg: zeroes and ones to create 0s and 1s respectively, with given length or shape. 

np.zeros(3)
np.ones((1,2))
np.empty((2,3))

#similarly arange is an array value based version of built in python range functions #which is used in first example. 
# Since numpy is focused on numerical computing, the data type, if not specified it will return float64 in many cases.

array([[0., 0., 0.],
       [0., 0., 0.]])

# array creation function:
1. Array
2. asarray
3. ones,ones_like : zero,zero_like
4. empty,empty_like
5. eye,identity 

In [10]:
# Data types for ndarrays: The data type is a special object containing the info the ndarray needs to interpret a chunk of memory as a particular type of data. 

arr1=np.array([1,2,3],dtype=np.float64)
arr2=np.array([1,2,3],dtype=np.int32)
arr1.dtype
arr2.dtype

# these is numpys flexibility for interacting data coming from other systems. 
#calling astype always create a new array (a copy of the data), even if the new dtype is the same as the old type. 

dtype('int32')

In [ ]:
# Arithmetic with numpy arrays: 

arr=np.array([[1,2,3,4],[5,6,7,8]])
arr*arr

# arithmetic operation with scalars propagate the scalar argument to each element in the array.
# comparison between arrays of the same size yield booleans arrays: for eg: arr2<arr 

# operation between differently sized arrays is called broadcasting. 

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [ ]:
# Basic index and slicing.

arr=np.arange(10)
arr[5:8]=6
arr_slice=arr[5:8]
arr_slice[1]=1234
arr

# the bare slice [:] will assign to all values in an array:
arr_slice[:]=64
arr

# to copy slice of an ndarray, explicitly copy the arrat=  arr[5:8].copy()

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [38]:
# Higher dimensional data: 
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

# the individual element can be accessed recursively ([0][1]) .but following can be better option. 
arr2d[0, 2]

arr3d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr3d
arr3d[1]

#both scalar and arrays can be assigned in arr3d[1]
old_values=arr3d[1].copy()
arr3d[1]=12
arr3d

arr3d[1]=old_values
arr3d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
# indexing with slices.
arr[1:4]

array([1, 2, 3])

In [ ]:
# for 2D data slicing is done as
arr2d[:2] # first two rows of the arr2d[:2]

#we can pass multiple slices:
arr2d[:2,1:] #by mixing integer index and slices, we get lowe dimensional slices.

array([[2, 3],
       [5, 6]])

In [ ]:
# to select second row but only first two column like so:
arr2d[1,:2]

# select third column but only first two rows
arr2d[:2,2]

array([4, 5])

In [48]:
# Note : a colon means to take entire axis, so we can slice only higher dimnesional axes:

arr2d[:,:1]
arr2d[:2,1:]=0
arr2d


array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])